### ISSUE TITLE
thinkpython.org is referenced, but is down

### ISSUE THREAD

**Issue by gregmarra** [AllenDowney/ThinkComplexity#1]
Below exercise 7.5, readers are instructed to find TurmiteWorld.py at http://thinkpython.org/swampy/ , but thinkpython.org appears to be a parked domain with only advertisements.

**Comment by AllenDowney** [comment]
Doh!  Should be thinkpython.com.

Will fix.  Thanks!

**Comment by gregmarra** [comment]
Actually when I went back and looked, it is .com. O.o

Sorry for the bother!
